export const MENU_OPEN = "MENU_OPEN";
export const MENU_CLOSE = "MENU_CLOSE";
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR ";
export const QUERY_PRODUCTS_BEGIN = "QUERY_PRODUCTS_BEGIN ";
export const QUERY_PRODUCTS_SUCCESS = "QUERY_PRODUCTS_SUCCESS";
export const QUERY_PRODUCTS_ERROR = "QUERY_PRODUCTS_ERROR ";
