export const MENU_OPEN = "MENU_OPEN";
export const MENU_CLOSE = "MENU_CLOSE";
export const GRID_VIEW = "GRID_VIEW";
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR ";
export const GET_QUERY_PRODUCTS_BEGIN = "GET_QUERY_PRODUCTS_BEGIN ";
export const GET_QUERY_PRODUCTS_SUCCESS = "GET_QUERY_PRODUCTS_SUCCESS";
export const GET_QUERY_PRODUCTS_ERROR = "GET_QUERY_PRODUCTS_ERROR";
export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";
export const GET_RECOMMENDED_PRODUCT_BEGIN = "GET_RECOMMENDED_PRODUCT_BEGIN";
export const GET_RECOMMENDED_PRODUCT_SUCCESS =
  "GET_RECOMMENDED_PRODUCT_SUCCESS";
export const GET_RECOMMENDED_PRODUCT_ERROR = "GET_RECOMMENDED_PRODUCT_ERROR ";
